name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest  # GitHub runs this on a virtual Linux machine

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # pulls your repo code into the workflow runner

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run code formatter (Black)
        run: |
          black --check .

      - name: Run linter (Flake8)
        run: |
          flake8 --ignore=E501,E203,W503

      - name: Run unit tests
        run: |
          pytest -v --maxfail=1 --disable-warnings